stages:
  - build

build:
  stage: build
  image: python:3.9-slim-buster # Use a Python-specific image that includes pip
  script:
    - echo "--- AutoHeal CI Starting Multi-Failure Test ---"
    - pip install psycopg2-binary
