import argparse
import json
import os
from pathlib import Path
from urllib import error, parse, request


def gitlab_request(method: str, url: str, token: str, data: dict | None = None) -> tuple[int, str]:
    payload = None
    headers = {"PRIVATE-TOKEN": token}
    if data is not None:
        payload = parse.urlencode(data).encode("utf-8")
        headers["Content-Type"] = "application/x-www-form-urlencoded"

    req = request.Request(url=url, method=method, data=payload, headers=headers)
    try:
        with request.urlopen(req, timeout=25) as resp:
            body = resp.read().decode("utf-8")
            return resp.status, body
    except error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        return exc.code, body
    except error.URLError as exc:
        return 0, f"Network error: {exc.reason}"
    except Exception as exc:
        return 0, f"Unexpected request error: {type(exc).__name__}: {exc}"


def update_ci_file(api_base: str, project_id: str, token: str, branch: str, target_file: str, ci_content: str) -> dict:
    encoded_file = parse.quote(target_file, safe="")
    url = f"{api_base}/projects/{project_id}/repository/files/{encoded_file}"

    data = {
        "branch": branch,
        "content": ci_content,
        "commit_message": "AutoHeal CI: Fix pipeline automatically",
    }

    status, body = gitlab_request("PUT", url, token, data)
    if status in (200, 201):
        return {"status": status, "operation": "updated", "response": body}

    # Fallback: create file if it does not exist yet.
    if status in (400, 404):
        create_status, create_body = gitlab_request("POST", url, token, data)
        if create_status in (200, 201):
            return {"status": create_status, "operation": "created", "response": create_body}
        return {"status": create_status, "operation": "create_failed", "response": create_body}

    return {"status": status, "operation": "update_failed", "response": body}


def trigger_pipeline(api_base: str, project_id: str, token: str, branch: str) -> dict:
    url = f"{api_base}/projects/{project_id}/pipeline"
    status, body = gitlab_request("POST", url, token, {"ref": branch})
    payload = None
    try:
        payload = json.loads(body)
    except json.JSONDecodeError:
        payload = {"raw": body}

    return {"status": status, "response": payload}


def latest_pipeline_status(api_base: str, project_id: str, token: str, branch: str) -> dict:
    params = parse.urlencode({"ref": branch, "per_page": 1})
    url = f"{api_base}/projects/{project_id}/pipelines?{params}"
    status, body = gitlab_request("GET", url, token)

    if status != 200:
        return {"status": status, "error": body}

    try:
        items = json.loads(body)
    except json.JSONDecodeError:
        return {"status": status, "error": "Invalid JSON from GitLab API"}

    if not items:
        return {"status": 200, "pipeline": None}

    latest = items[0]
    return {
        "status": 200,
        "pipeline": {
            "id": latest.get("id"),
            "status": latest.get("status"),
            "web_url": latest.get("web_url"),
            "ref": latest.get("ref"),
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Auto-fix GitLab pipeline by updating .gitlab-ci.yml and re-triggering pipeline")
    parser.add_argument("--ci-file", default=".gitlab-ci-fixed.yml", help="Source CI file generated by AutoHeal")
    parser.add_argument("--target-file", default=".gitlab-ci.yml", help="Target file path in GitLab repository")
    parser.add_argument("--status-only", action="store_true", help="Only fetch latest pipeline status")
    args = parser.parse_args()

    token = os.getenv("GITLAB_TOKEN", "").strip()
    project_id = os.getenv("GITLAB_PROJECT_ID", "").strip()
    branch = os.getenv("GITLAB_BRANCH", "main").strip() or "main"
    api_base = os.getenv("GITLAB_API_BASE", "https://gitlab.com/api/v4").strip() or "https://gitlab.com/api/v4"

    if not token or not project_id:
        print(json.dumps({"error": "Missing credentials in sidebar"}, indent=2))
        return

    # GitLab project ID must be numeric (e.g., "123456"), not a project path/hash.
    if not project_id.isdigit():
        print(json.dumps({"error": "GITLAB_PROJECT_ID must be a numeric string (example: \"123456\")"}, indent=2))
        return

    try:
        if args.status_only:
            print(json.dumps(latest_pipeline_status(api_base, project_id, token, branch), indent=2))
            return

        source_path = Path(args.ci_file)
        if not source_path.exists():
            print(json.dumps({"error": f"CI source file not found: {source_path}"}, indent=2))
            return

        ci_content = source_path.read_text(encoding="utf-8")

        update_result = update_ci_file(api_base, project_id, token, branch, args.target_file, ci_content)
        pipeline_result = trigger_pipeline(api_base, project_id, token, branch)

        output = {
            "update": update_result,
            "pipeline_trigger": pipeline_result,
        }

        print(json.dumps(output, indent=2))
    except Exception as exc:
        print(
            json.dumps(
                {
                    "error": "Unexpected failure while processing GitLab auto-fix",
                    "details": f"{type(exc).__name__}: {exc}",
                },
                indent=2,
            )
        )


if __name__ == "__main__":
    main()
